'use strict';
const slides=[...document.querySelectorAll('.slide')],dots=[...document.querySelectorAll('#dots button')];
let current=0;const modal=document.querySelector('#lightbox');
function go(index,update=true){current=Math.max(0,Math.min(slides.length-1,index));slides.forEach((slide,i)=>{slide.classList.toggle('active',i===current);slide.classList.toggle('before',i<current);slide.inert=i!==current;slide.setAttribute('aria-hidden',String(i!==current));if(i===current)slide.scrollTop=0;});dots.forEach((dot,i)=>{if(i===current)dot.setAttribute('aria-current','step');else dot.removeAttribute('aria-current');});document.querySelector('#counter').innerHTML=`0${current+1} <i>/ 05</i>`;document.querySelector('#progress').style.width=`${(current+1)/slides.length*100}%`;document.querySelector('#prev').disabled=current===0;document.querySelector('#next').disabled=current===slides.length-1;if(update)history.replaceState(null,'','#'+slides[current].id);}
document.querySelectorAll('[data-go]').forEach(button=>button.addEventListener('click',()=>{go(Number(button.dataset.go));dots[current].focus({preventScroll:true});}));
document.querySelector('#prev').onclick=()=>go(current-1);document.querySelector('#next').onclick=()=>go(current+1);
document.addEventListener('keydown',e=>{if(modal.open||e.altKey||e.ctrlKey||e.metaKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(['ArrowRight','PageDown','ArrowLeft','PageUp','Home','End'].includes(e.key)){e.preventDefault();go(e.key==='Home'?0:e.key==='End'?slides.length-1:current+(['ArrowRight','PageDown'].includes(e.key)?1:-1));}});
let start=null;const deck=document.querySelector('#deck');deck.addEventListener('touchstart',e=>{if(e.touches.length===1)start={x:e.touches[0].clientX,y:e.touches[0].clientY};},{passive:true});deck.addEventListener('touchend',e=>{if(!start)return;const dx=e.changedTouches[0].clientX-start.x,dy=e.changedTouches[0].clientY-start.y;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.6)go(current+(dx<0?1:-1));start=null;},{passive:true});deck.addEventListener('touchcancel',()=>start=null);
document.querySelectorAll('[data-image]').forEach(button=>button.onclick=()=>{const img=document.querySelector('#large-image');img.src=button.dataset.image;img.alt=button.querySelector('img').alt;modal.showModal();});document.querySelector('#close-modal').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal)modal.close();});
const fs=document.querySelector('#fullscreen');if(!document.fullscreenEnabled)fs.hidden=true;fs.onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{fs.hidden=true;}};document.addEventListener('fullscreenchange',()=>{fs.setAttribute('aria-label',document.fullscreenElement?'Keluar layar penuh':'Aktifkan layar penuh');fs.querySelector('span').textContent=document.fullscreenElement?'Keluar layar penuh':'Layar penuh';});
function fromHash(){const index=slides.findIndex(s=>'#'+s.id===location.hash);go(index<0?0:index,false);}window.addEventListener('hashchange',fromHash);fromHash();
